//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Download.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContentStatic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentStatic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Download.Common.Resources.ContentStatic", typeof(ContentStatic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ButtonStart {
            get {
                return ResourceManager.GetString("ButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string ButtonStop {
            get {
                return ResourceManager.GetString("ButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop program?.
        /// </summary>
        public static string CancelProgramMessage {
            get {
                return ResourceManager.GetString("CancelProgramMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelProgramTitle {
            get {
                return ResourceManager.GetString("CancelProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit form.
        /// </summary>
        public static string ConfirmExitFormTitle {
            get {
                return ResourceManager.GetString("ConfirmExitFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateProjectButtonText {
            get {
                return ResourceManager.GetString("CreateProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project Folder.
        /// </summary>
        public static string CreateProjectText {
            get {
                return ResourceManager.GetString("CreateProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Data..
        /// </summary>
        public static string DuplicateData {
            get {
                return ResourceManager.GetString("DuplicateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} row(s) do not save. Do you want to save it?.
        /// </summary>
        public static string ExistFormHaveDataNotSave {
            get {
                return ResourceManager.GetString("ExistFormHaveDataNotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really close program?.
        /// </summary>
        public static string ExitFormMessage {
            get {
                return ResourceManager.GetString("ExitFormMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Program?.
        /// </summary>
        public static string ExitFormTitle {
            get {
                return ResourceManager.GetString("ExitFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Html is required..
        /// </summary>
        public static string HtmlContentRequired {
            get {
                return ResourceManager.GetString("HtmlContentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is requied..
        /// </summary>
        public static string InputRequied {
            get {
                return ResourceManager.GetString("InputRequied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Name is required..
        /// </summary>
        public static string LinkNameRequired {
            get {
                return ResourceManager.GetString("LinkNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link really exist..
        /// </summary>
        public static string LinkReallyExist {
            get {
                return ResourceManager.GetString("LinkReallyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links is required..
        /// </summary>
        public static string LinkRequired {
            get {
                return ResourceManager.GetString("LinkRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project has been canceled..
        /// </summary>
        public static string MessageCancel {
            get {
                return ResourceManager.GetString("MessageCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software has error. Please capture error screen and  to contact with me:
        ///email: an.huynhviet@hotmail.com.
        ///skype: an.huynhviet.
        /// </summary>
        public static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Successfully..
        /// </summary>
        public static string MessageSuccess {
            get {
                return ResourceManager.GetString("MessageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name really exist..
        /// </summary>
        public static string PageNameReallyExist {
            get {
                return ResourceManager.GetString("PageNameReallyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page name is required..
        /// </summary>
        public static string PageNameRequired {
            get {
                return ResourceManager.GetString("PageNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        public static string RequiredTitle {
            get {
                return ResourceManager.GetString("RequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from software!!!.
        /// </summary>
        public static string TitleMessage {
            get {
                return ResourceManager.GetString("TitleMessage", resourceCulture);
            }
        }
    }
}
