//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CopyHtmlWebSite.MainApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegexResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegexResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CopyHtmlWebSite.MainApp.Properties.RegexResource", typeof(RegexResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;base [^&gt;]*/&gt;.
        /// </summary>
        internal static string BaseTag {
            get {
                return ResourceManager.GetString("BaseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ([&quot;|&apos;|\\]).
        /// </summary>
        internal static string ContentImageInCss {
            get {
                return ResourceManager.GetString("ContentImageInCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data:(?&lt;mime&gt;[\w/\-\.]+);(?&lt;encoding&gt;\w+),(?&lt;data&gt;.*).
        /// </summary>
        internal static string ImageBase64 {
            get {
                return ResourceManager.GetString("ImageBase64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @import ([&quot;&quot;&apos;])(?&lt;url&gt;[^&quot;&quot;&apos;]+)\1|url\(([&quot;&quot;&apos;]?)(?&lt;url&gt;[^&quot;&quot;&apos;)]+)\2\).
        /// </summary>
        internal static string ImageInCss {
            get {
                return ResourceManager.GetString("ImageInCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /$.
        /// </summary>
        internal static string LastSlashCharacter {
            get {
                return ResourceManager.GetString("LastSlashCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ../.
        /// </summary>
        internal static string PrefixLink {
            get {
                return ResourceManager.GetString("PrefixLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \s+.
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [^0-9a-zA-Z]+.
        /// </summary>
        internal static string SpecialChar {
            get {
                return ResourceManager.GetString("SpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \/\/[\w\-_]+(\.[\w\-_]+)+([\w\-\.,@?^=%&amp;amp;:/~\+#]*[\w\-\@?^=%&amp;amp;/~\+#])?.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (url|URL|Url|@import |\(|\)|&apos;|&quot;).
        /// </summary>
        internal static string UrlImageInCss {
            get {
                return ResourceManager.GetString("UrlImageInCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;|&quot;.
        /// </summary>
        internal static string UrlIntoQuotation {
            get {
                return ResourceManager.GetString("UrlIntoQuotation", resourceCulture);
            }
        }
    }
}
